// === ll 题库 ===
// 自动从 index.html 提取
(function(){
  subjectData['ll'] = [

{id:'ll1',type:'choice',diff:'easy',year:'2025',chapter:'method',text:'对外汉语教学的根本目的是？',options:['A.教授语法','B.培养阅读能力','C.培养交际能力','D.传播文化'],answer:'C'},
{id:'ll2',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'"中介语"是指？',options:['A.双语翻译','B.二语学习者语言系统','C.口语书面语之间'],answer:'B'},
{id:'ll3',type:'choice',diff:'easy',year:'2025',chapter:'theory',text:'负迁移是指？',options:['A.母语的促进作用','B.母语的阻碍作用','C.既不好也不坏'],answer:'B'},
{id:'ll4',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'功能法的核心是？',options:['A.功能和意念为纲','B.语法为纲','C.句型操练'],answer:'A'},
{id:'ll5',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'四大教学环节的中心是？',options:['A.总体设计','B.教材编写','C.课堂教学','D.测试'],answer:'C'},
{id:'ll6',type:'choice',diff:'easy',year:'2025',chapter:'method',text:'20世纪80年代后转向以什么为中心？',options:['A.教师','B.学生','C.教材','D.考试'],answer:'B'},
{id:'ll7',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'听说法的特点是？',options:['A.注重读写','B.句型操练模仿','C.语法规则'],answer:'B'},
{id:'ll8',type:'choice',diff:'hard',year:'2025',chapter:'theory',text:'情感过滤假说认为影响最大的是？',options:['A.语法能力','B.母语水平','C.输入数量','D.焦虑和自信'],answer:'D'},
{id:'ll9',type:'choice',diff:'mid',year:'2025',chapter:'theory',text:'"偏误"是？',options:['A.系统性的','B.偶然的','C.语音的'],answer:'A',explain:'偏误是系统性的。'},
{id:'ll10',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'水平测试（HSK）的目的是？',options:['A.测量水平','B.检查课程','C.诊断问题','D.测量潜能'],answer:'A'},
{id:'ll11',type:'fill',diff:'easy',year:'2025',chapter:'method',text:'教材编写五原则：实用性、知识性、针对性、科学性、______。',options:[],answer:'趣味性'},
{id:'ll12',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'任务型教学法中"前任务"阶段不包括？',options:['A.展示地图','B.布置小组任务','C.讨论词汇'],answer:'B'},
{id:'ll13',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'最能体现"意义优先"的是？',options:['A.示范跟读','B.用过去时回答','C.角色扮演点餐'],answer:'C'},
{id:'ll14',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'第一部对外汉语教材是？',options:['A.《会话301句》','B.《基础汉语》','C.《实用汉语课本》'],answer:'C'},
{id:'ll15',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'中国传统的"精读课"属于？',options:['A.语法课','B.阅读课','C.听说读写综合性课','D.文化课'],answer:'C'},
{id:'ll16',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'课型按什么划分？',options:['A.语言材料','B.语言知识','C.语体','D.语言技能'],answer:'D'},
{id:'ll17',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'任务驱动法强调？',options:['A.教师为中心','B.学生自主探索','C.语法规则'],answer:'B'},
{id:'ll18',type:'choice',diff:'hard',year:'2025',chapter:'theory',text:'听说法的语言学基础是？',options:['A.历史比较语言学','B.结构主义语言学','C.转换生成语言学'],answer:'B'},
{id:'ll19',type:'judge',diff:'easy',year:'2025',chapter:'theory',text:'信息越多学习效果越好。',options:[],answer:'×',explain:'认知负荷理论认为信息量过大会降低效果。'},
{id:'ll20',type:'judge',diff:'mid',year:'2025',chapter:'theory',text:'文化教学应以中国官方立场为唯一标准。',options:[],answer:'×'},
{id:'ll21',type:'judge',diff:'easy',year:'2025',chapter:'theory',text:'外在动机比内在动机更能促进长期学习。',options:[],answer:'×'},
{id:'ll22',type:'judge',diff:'easy',year:'2025',chapter:'method',text:'教授语法应先讲解规则再情境练习。',options:[],answer:'×'},
{id:'ll23',type:'judge',diff:'mid',year:'2025',chapter:'theory',text:'交际法中教师是管理者权威。',options:[],answer:'×'},
{id:'ll24',type:'judge',diff:'mid',year:'2025',chapter:'method',text:'对外汉语只需要教语言知识即可。',options:[],answer:'×'},
{id:'ll25',type:'fill',diff:'mid',year:'2025',chapter:'method',text:'对外汉语教学既是第二语言教学又是______教学。',options:[],answer:'外语'},
{id:'ll26',type:'fill',diff:'mid',year:'2025',chapter:'method',text:'四大教学环节包括总体设计、教材编写、课堂教学和______。',options:[],answer:'测试'},
{id:'ll27',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'"汉语桥"考查什么？',options:['A.汉语知识','B.运用能力','C.文化知识','D.以上都是'],answer:'D'},
{id:'ll28',type:'choice',diff:'hard',year:'2025',chapter:'method',text:'中级阶段词汇量要求约？',options:['A.1000-2000','B.2000-3000','C.3000-4000','D.4000-5000'],answer:'C'},
{id:'ll29',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'"入乡随俗"体现？',options:['A.文化适应','B.文化冲突','C.文化休克'],answer:'A'},
{id:'ll30',type:'fill',diff:'mid',year:'2025',chapter:'method',text:'语音教学中声调教学一靠模仿二靠______。',options:[],answer:'记忆'},
{id:'ll31',type:'judge',diff:'mid',year:'2025',chapter:'method',text:'国际汉语教师职业道德规范要求教师在课堂上必须使用标准普通话，不得夹杂地方方言。',options:[],answer:'×',explain:'规范使用普通话是要求，但允许适度地方口音，关键是避免影响交流。'},
{id:'ll32',type:'judge',diff:'mid',year:'2025',chapter:'theory',text:'根据认知负荷理论，教学活动中呈现的信息量越多，学习效果越好。',options:[],answer:'×',explain:'认知负荷理论认为信息量过大会导致认知过载，影响学习效果。'},
{id:'ll33',type:'judge',diff:'mid',year:'2025',chapter:'theory',text:'在汉语教学中，所有文化点的讲解都必须以中国官方立场为唯一标准。',options:[],answer:'×',explain:'文化教学应客观介绍多元文化，鼓励平等对话，而非强制认同单一立场。'},
{id:'ll34',type:'judge',diff:'easy',year:'2025',chapter:'theory',text:'根据动机理论，外在动机比内在动机更能促进语言学习的长期发展。',options:[],answer:'×',explain:'内在动机更可持续，外在动机可能引发功利性学习行为。'},
{id:'ll35',type:'judge',diff:'mid',year:'2025',chapter:'theory',text:'根据对比分析法，汉语"你"和英语"I"在指代对象上完全等价。',options:[],answer:'×',explain:'两者指代对象和语法功能不同。'},
{id:'ll36',type:'choice',diff:'easy',year:'2025',chapter:'method',text:'以下哪种教学方法强调学生自主探索知识？',options:['A.讲授法','B.任务驱动法','C.情景教学法','D.交际教学法'],answer:'B',explain:'任务驱动法以任务为导向，让学生在完成任务过程中自主探索知识。'},
{id:'ll37',type:'choice',diff:'easy',year:'2025',chapter:'theory',text:'在跨文化交际中，"入乡随俗"体现的是？',options:['A.文化适应','B.文化冲突','C.文化休克','D.文化偏见'],answer:'A',explain:'"入乡随俗"是适应当地文化习俗，体现文化适应。'},
{id:'ll38',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'对外汉语教学中，中级阶段的词汇量要求大约是？',options:['A.1000-2000','B.2000-3000','C.3000-4000','D.4000-5000'],answer:'C',explain:'中级阶段词汇量要求一般在3000-4000左右。'},
{id:'ll39',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'对外汉语课堂上，教师纠正学生发音时，哪种方式较合适？',options:['A.直接指出并示范','B.让其他学生指出','C.先肯定再委婉指出并示范','D.不纠正等学生自己发现'],answer:'C',explain:'先肯定再委婉指出并示范，既能保护学生积极性又能有效纠正。'},
{id:'ll40',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'以下哪种句式用于表达建议？',options:['A.把字句','B.被字句','C.是字句','D.应该句'],answer:'D',explain:'应该句常用来表达建议。'},
{id:'ll41',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'下列哪个汉字的笔画顺序是正确的？',options:['A.水','B.火','C.土','D.山'],answer:'A',explain:'水字的笔画顺序是竖钩、横撇、撇、捺。'},
{id:'ll42',type:'choice',diff:'mid',year:'2025',chapter:'theory',text:'在评估学习者口语流利度时，哪个指标最符合教学大纲要求？',options:['A.单词拼写错误数量','B.语速是否达标','C.声调错误百分比','D.回答的完整性和逻辑连贯性'],answer:'D',explain:'流利度考察语言连贯性和自然度。'},
{id:'ll43',type:'choice',diff:'hard',year:'2025',chapter:'theory',text:'根据二语习得理论，对声调掌握效果影响最大的因素是？',options:['A.母语声调系统相似度','B.起始年龄','C.声调输入频率和清晰度','D.音乐学习背景'],answer:'C',explain:'声调掌握受输入环境影响最大。'},
{id:'ll44',type:'choice',diff:'hard',year:'2025',chapter:'method',text:'根据任务型教学法，哪个环节不属于前任务阶段？',options:['A.展示地图情境','B.布置小组任务','C.讨论可能用到的词汇','D.提供语法点讲解'],answer:'B',explain:'布置具体任务属于任务环阶段。'},
{id:'ll45',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'交际语言教学法强调以什么为中心？',options:['A.教师','B.教材','C.学生','D.考试'],answer:'C',explain:'交际语言教学法强调以学生为中心。'},
{id:'ll46',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'全身反应法TPR的主要特点是什么？',options:['A.强调语法翻译','B.通过身体动作回应指令','C.注重读写训练','D.强调文化教学'],answer:'B',explain:'TPR通过身体动作回应语言指令。'},
{id:'ll47',type:'choice',diff:'mid',year:'2025',chapter:'theory',text:'克拉申的情感过滤假说认为哪个因素影响语言习得？',options:['A.年龄','B.焦虑水平','C.母语','D.性别'],answer:'B',explain:'焦虑水平高会阻碍语言输入的有效吸收。'},
{id:'ll48',type:'choice',diff:'easy',year:'2025',chapter:'theory',text:'偏误与失误的主要区别是什么？',options:['A.偏误是系统性的失误是偶然的','B.偏误是偶然的失误是系统性的','C.两者没有区别','D.偏误是口语问题失误是书面问题'],answer:'A',explain:'偏误是系统性的，反映中介语的规律特征。'},
{id:'ll49',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'以下哪种教学活动最能体现交际性原则？',options:['A.抄写生词十遍','B.角色扮演点餐场景','C.朗读课文','D.做语法选择题'],answer:'B',explain:'角色扮演模拟真实交际场景。'},
{id:'ll50',type:'judge',diff:'easy',year:'2025',chapter:'method',text:'对外汉语教学中，教师应始终保持课堂上的权威地位。',options:[],answer:'×',explain:'教师应是引导者和促进者。'},
{id:'ll51',type:'judge',diff:'easy',year:'2025',chapter:'theory',text:'中介语是二语学习者形成的独立语言系统，介于母语和目的语之间。',options:[],answer:'✓',explain:'中介语具有系统性、动态性和可渗透性。'},
{id:'ll52',type:'judge',diff:'mid',year:'2025',chapter:'method',text:'任务型教学法中，前任务阶段不需要任何语言输入的铺垫。',options:[],answer:'×',explain:'前任务阶段需要预热活动。'},
{id:'ll53',type:'judge',diff:'mid',year:'2025',chapter:'method',text:'根据交际语言教学法，课堂上的所有活动都必须模拟真实交际情境。',options:[],answer:'×',explain:'并非所有活动都必须模拟真实情境。'},
{id:'ll54',type:'judge',diff:'hard',year:'2025',chapter:'method',text:'在对外汉语教学中，文化教学的目标是让学习者完全认同中国传统文化。',options:[],answer:'×',explain:'文化教学的目标是促进跨文化理解。'},
{id:'ll55',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'教材编写五原则中不包括以下哪项？',options:['A.针对性','B.科学性','C.趣味性','D.政治性'],answer:'D',explain:'教材编写五原则是针对性、实用性、科学性、趣味性、知识性。'},
{id:'ll56',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'HSK的全称是什么？',options:['A.汉语水平考试','B.汉语能力测试','C.国际汉语教师考试','D.中国语文考试'],answer:'A',explain:'HSK是汉语拼音Hanyu Shuiping Kaoshi的缩写。'},
{id:'ll57',type:'choice',diff:'mid',year:'2025',chapter:'theory',text:'语言迁移中，母语对二语学习的促进作用称为？',options:['A.正迁移','B.负迁移','C.零迁移','D.逆迁移'],answer:'A',explain:'母语与目的语相似时产生正迁移，促进学习。'},
{id:'ll58',type:'choice',diff:'mid',year:'2025',chapter:'method',text:'对外汉语教学中，综合课又称为？',options:['A.精读课','B.口语课','C.听力课','D.写作课'],answer:'A',explain:'综合课在中国对外汉语教学传统中常被称为精读课。'},
{id:'ll59',type:'choice',diff:'hard',year:'2025',chapter:'theory',text:'听说法的语言学基础是什么？',options:['A.历史比较语言学','B.结构主义语言学','C.转换生成语言学','D.功能语言学'],answer:'B',explain:'听说法以结构主义语言学和行为主义心理学为基础。'},
{id:'ll60',type:'choice',diff:'hard',year:'2025',chapter:'theory',text:'交际法的语言学基础是什么？',options:['A.结构主义语言学','B.转换生成语言学','C.社会语言学','D.历史比较语言学'],answer:'C',explain:'交际法以社会语言学为基础。'},

  ];
})();
